name: Publish Package
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup .npmrc
        env:
          NPM_RC: ${{ secrets.NPM_RC }}
        run: echo "$NPM_RC" >> .npmrc

      - name: Update package version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          jq ".version = \"$VERSION\"" package.json > temp.json && mv temp.json package.json
          npm install  # package-lock.json の更新

      - name: Commit updated package.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Update package version to $VERSION"

      - name: Push updated package.json
        run: git push origin main

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
